# Generated by Django 3.2.6 on 2021-08-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discounted_Price', models.FloatField()),
                ('category', models.CharField(max_length=300)),
                ('discription', models.TextField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
